version: '2'
services:
  web:
    build: .
    ports:
      - "8000:3000"
    depends_on:
      - mongo
    networks:
      - internal
  mongo:
    image: mongo:3.2
    command: mongod --smallfiles --config /data/mongod.conf.yml
    volumes:
      - .:/data
    networks:
      - internal

networks:
  internal:
    ipam:
      config:
        - subnet: 192.168.2.0/24
